language: node_js
node_js:
    - "10.*"
services:
    - mysql
cache: yarn
before_install:
    - mysql -e 'CREATE DATABASE treevity_test;'
install:
    - yarn
before_script:
    - yarn lint
    - yarn typeorm migration:run
    - yarn build
script:
    - yarn test
